### PR TITLE
Fixes #5 fail to return output table

### LINKED ISSUE #5: R Toolbox - Release > 7.0.0 fail to return output table
`getSimulationResults `returns per column only one value, the remaining are NA
It can be shown, that the call to `RDCI_GetOutputTable` in the DLL is returning differently compared to relase 6.3.2.

The attached example code prints a vector of number with 6.3.2 (rightly), but a single number with 7.0.0 or 7.1.0

[miniExampleToDemoToolboxBug.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/892965/miniExampleToDemoToolboxBug.zip)
[testSim.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/892966/testSim.zip)

### PR DESCRIPTION
**Pull request by Yuri05**
set all outputs persistable in initSimulation.R

### CODE REVIEW

File: src/code/initSimulation.R [hunk 1]
```diff
@@ -180,7 +180,19 @@ initSimulation <- function(XML = "", ParamList = numeric(0), whichInitParam = ""
 	{
 	  stop(.Call("RDCI_GetLastError"));
 	}
-
+	
+	# for the moment set all output variables/observer as persistable, so that their values are accessible after processSimulation
+	# this should be changed in the future to setting only otputs of interest  as persistable
```
Comment (msevestre) [inline src/code/initSimulation.R:185]: Please add an issue for that so that we do not forget!

File: src/code/initSimulation.R [hunk 2]
```diff
@@ -180,7 +180,19 @@ initSimulation <- function(XML = "", ParamList = numeric(0), whichInitParam = ""
 	{
 	  stop(.Call("RDCI_GetLastError"));
 	}
-
+	
+	# for the moment set all output variables/observer as persistable, so that their values are accessible after processSimulation
+	# this should be changed in the future to setting only otputs of interest  as persistable 
+	retval = .Call('RDCI_Invoke', DCI_Info$Handle, 'SetAllOutputsPersistable', "");
+	if (is.character(retval) & retval != "") 
+    {
```
Comment (msevestre) [inline src/code/initSimulation.R:188]: It seems that there is some serious formatting issues in this file. Indentation is all wrong

File: src/code/initSimulation.R [hunk 3]
```diff
@@ -180,7 +180,19 @@ initSimulation <- function(XML = "", ParamList = numeric(0), whichInitParam = ""
...
+      stop(retval)
+    }
+	if (retval == 0)
```
Comment (msevestre) [inline src/code/initSimulation.R:191]: return value of 0 is error?? 0 as return values actually stands for success normally. This is very confusing

File: src/code/initSimulation.R (hunk 1 above)
Comment (Yuri05) [reply src/code/initSimulation.R:185]: Must be done both for R- and Matlab-Toolbox

File: src/code/initSimulation.R (hunk 3 above)
Comment (CandideThunder) [reply src/code/initSimulation.R:191]: indeed. `.Call` returns "R object constructed in the compiled code". So question is what `RDCI_invoke` returns in case of error: An errormessage or a 0 ?

**Review by CandideThunder — APPROVED** [review]

File: src/code/initSimulation.R (hunk 1 above)
Comment (Yuri05) [reply src/code/initSimulation.R:185]: done: #9

**Comment by msevestre** [comment]
@Yuri05 I have made some comments on this PR. Not sure if you want to address them or not. If not, please merge

File: src/code/initSimulation.R (hunk 3 above)
Comment (Yuri05) [reply src/code/initSimulation.R:191]: An error message, 0 will be returned only if clearing the previous DCI error message in the compiled DCIR code fails, which is virtually impossible.

Comment (msevestre) [reply src/code/initSimulation.R:191]: What I meant is that 0 is in all best practices recipes a return code for success and not failure. SO this code is doing exactly the opposite as what is expected

**Comment by msevestre** [comment]
Indentation is still out of wack.

File: src/code/initSimulation.R (hunk 3 above)
Comment (Yuri05) [reply src/code/initSimulation.R:191]: Most DCI functions return 1 for success and 0 for error. Actually it's a success flag what is being returned, not the error code.
Unless we don't want to change the whole DCI Core (and we don't :-), we have to accept this
