### PR TITLE
Fixes #32 get parameter by name

### LINKED ISSUE #32: getParameter() fails when parameter is accessed via path name and no variables were initialized.
**Problem:**

When trying the get a parameter via path name from a simulation with no initialized parameters, a zero-index is returned.
```

standard_dci_info <- initSimulation(XML=simModelXML, whichInitParam="none")
getParameter(path_id="black american girl|Organism|Age", DCI_Info = dci_info, options=options)

$Value
numeric(0)

$Index
[1] 0
```

Accessing the same parameter via numerical id works:

```
getParameter(path_id=48, DCI_Info = dci_info, options=options)

$Value
[1] 0

$Index
[1] 35
```

### PR DESCRIPTION
**Pull request by PavelBal**
- Add test for getParameter by path name
- Add test for getParameter with invalid path
- Add test for getParameter by path name containing brackets
- Automaticall escape "(", ")", "[", and "]"
- Add a warning if manual escaping of "(", ")", "[", or "]" is detected
- findTableIndex.R always returns "integer(0)" instead of "0" if the parameter could not be found

### CODE REVIEW

File: src/code/findTableIndex.R [hunk 1]
```diff
@@ -34,18 +34,33 @@ findTableIndex <- function(path_id = numeric(0), tableID = numeric(0), isReferen
   		indx <- 1:counts
   		if (path_id != '*')
   		{
```
Comment (msevestre) [inline src/code/findTableIndex.R:36]: I like that!,

**Review by StephanSchaller — APPROVED** [review]
I like it!

**Review by sfrechen — APPROVED** [review]

**Comment by msevestre** [comment]
All right let's merge that baby. Thanks @PavelBal

**Comment by StephanSchaller** [comment]
The first community contribution! 🍾
